sonar.exclusions=pnpm-lock.yaml,**/pnpm-lock.yaml,**/node_modules/**,**/dist/**,**/.turbo/**,**/.next/**,**/playwright-report/**,**/drizzle/*.sql,**/drizzle/**/*.sql
sonar.cpd.exclusions=pnpm-lock.yaml,**/pnpm-lock.yaml,**/drizzle/*.sql,**/drizzle/**/*.sql
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=*pnpm-lock.yaml
