sonar.exclusions=pnpm-lock.yaml,**/pnpm-lock.yaml,**/node_modules/**,**/dist/**,**/.turbo/**,**/.next/**,**/playwright-report/**
sonar.cpd.exclusions=pnpm-lock.yaml,**/pnpm-lock.yaml
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=**/pnpm-lock.yaml
